# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHQ-ttG1V1ZssM7U5dTON5Ogq4BMrhd0

# Funções Lambda e Funções Anonimas
"""

media = lambda a,b : (a+b)/2
media(4,2)

import math

raiz = lambda x:math.sqrt(x)
raiz(16)

"""# List Comprehension"""

squares = [x**2 for x in range(10)]
print(squares)

"""Funções Map"""

import math
raiz = list(map(lambda x: math.sqrt(x), squares))
print(raiz)

"""# Listas"""

lista = [1,2,3]
tupla = (1,2,3)
dicionario = {1: 'um' ,2: 'dois' , 3: 'tres'}
# type(lista)
# type(tupla)
# type(dicionario)
tupla[1]
dicionario.get(3)

"""# Formatação de String"""

nome = 'Stella'
idade = 17
print(f'{nome} tem {idade} anos')

altura = 1.99
peso = 50
print(f'Tem {altura} metros e pesa {peso}kg')

"""# Laço de para"""

for i in range(3):
  print(i)

"""# Laço enquanto"""

x = 0
while (x<5):
  print(x)
  x +=1

"""# Estrututa se"""

if (x==5): print(x)