# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muJ_wDEmo_xWnFvCVcL5Kd-AXYHgYD9u

Pip é o gerenciador de pacotes do python, responsável pela instalação das bibliotecas usadas ela linguagem.
"""

pip install nltk textblob

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from textblob import TextBlob

"""Baixar os componentes NLTK necessários"""

nltk.download('punkt')
nltk.download('stopwords')

"""Função de pré processamento de texto"""

def preprocesso(texto):
  #Tokenização
  tokens = word_tokenize(texto.lower())

  #Remover os espaços das frases
  espaços = set(stopwords.words('english'))

  #Filtrando os tokens
  tokens_filtrados = [palavra for palavra in tokens if palavra.isalnum() and palavra not in espaços]

  #Retorno da função
  return ' '.join(tokens_filtrados)

"""Função para analise de sentimentos"""

def sentimentos(texto):

  #Limpando o texto digitado
  texto_limpo = preprocesso(texto)

  #Análise de sentimento do texto
  blob = TextBlob(texto_limpo)

  #Aplicando a polaridade do sentimento
  sentimento = blob.sentiment.polarity

  #Retornando a pontuação
  return sentimento

"""Listas de frases com sentimento"""

frases = [
    "The app exceeded my expectations.",
    "Constant updates with great news, I recommend it.",
    "Best app in its category, beautiful design and complete functions!",
    "Very useful! Does what it promises quickly and efficiently.",
    "After the last update, performance got worse. Needs adjustments.",
    "Lots of advertisements that interfere with use, I hated it.",
    "Customer service takes too long to respond and does not resolve the issue.",
    "I found the design confusing and difficult to navigate.",
    "It needs a lot of improvements, I don't recommend it.",
    "Works flawlessly without crashes.",
    "Easy to use, even for beginners.",
    "Delivers what it promises, very good!",
    "Very attentive technical support.",
    "I get frequent updates, that's great!",
    "Perfect functionality, no bugs.",
    "Very useful for my routine.",
    "The interface could be faster.",
    "The performance sometimes drops.",
    "The quality of the features is excellent.",
    "Best app I've ever used.",
    "The latest update improved a lot!",
    "Simple, direct, and functional.",
    "Missing a few options, but works well.",
    "It has improved a lot since the last version.",
    "Clean interface and easy to understand.",
    "Support is fast and efficient.",
    "Works offline, which is great.",
    "There are still some bugs to fix.",
    "I really liked the minimalist design.",
    "Sometimes it takes a while to load.",
    "Meets all my expectations.",
    "Easy to set up and use.",
    "The overall experience was very good.",
    "Helps a lot with personal organization.",
    "Light and well-optimized app.",
    "Needs improvements in the security aspect.",
    "Great integration with other services.",
    "The usability is perfect!",
    "The app crashes frequently, needs fixing.",
    "Could be faster on older devices.",
    "I recommend it for anyone seeking efficiency.",
    "The performance is impressive!",
    "It lacks some customization options.",
    "Amazing features for managing tasks.",
    "It has improved a lot with the latest updates.",
    "Needs improvements in notifications.",
    "I really liked the automatic features.",
    "Requires too many permissions to work.",
    "Customer support could be faster.",
    "Very light and doesn't take up much space on your cell phone. I recommend."
]

"""Exibindo a frase e sua pontuação"""

pontos = []
for comentario in frases:
  nivel = sentimentos(comentario)
  print(f"Comentario: {comentario}\nPontuação:{round(nivel,2)}\n")
  pontos.append(round(nivel,2))

import matplotlib.pyplot as plt
import numpy as np

x = np.array(pontos)
y = np.array(pontos)

plt.plot(x,y, 'o')
plt.show()