# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eW9KP_dktiHQTTVi6bnyz9vbVhBzs757

# Introdução a Matplotlib

# Importando Matplotlib e NumPy
"""

import matplotlib.pyplot as plt
import numpy as np

"""# Inserindo vertices"""

x = np.array([0,0,0,1,1,2,3,3,3,3,4,6,6,8,10])
y = np.array([5,10,10,5,5,15,15,20,20,0,25,0,10,25,10])

"""# Plotagem e visualização"""

plt.plot(x,y,'o')
plt.show()